# Generated by Django 5.1.1 on 2024-09-19 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultitenantApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedSubtitles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=20)),
                ('subtitle_text', models.TextField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MultitenantApp.uploadedvideos')),
            ],
        ),
    ]
