# Generated by Django 5.1.1 on 2024-09-19 15:46

import MultitenantApp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MultitenantApp', '0002_uploadedsubtitles'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubtitleTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle_path', models.FileField(upload_to=MultitenantApp.models.upload_to_subtitles)),
                ('srclang', models.CharField(blank=True, max_length=10, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='MultitenantApp.uploadedvideos')),
            ],
        ),
    ]
