# Generated by Django 5.1.1 on 2024-09-20 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MultitenantApp', '0003_subtitletrack'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedSubtitles',
        ),
    ]
